//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TextDemo.rc
//
#define IDR_MAINFRAME					128
#define IDD_TEXTDEMO_DIALOG				102
#define IDC_EDT_END_CREDIT				1000
#define IDC_STATIC_TEXT_DISPLAY 		1001
#define IDC_STATIC_TEXT_PREVIEW 		1002
#define IDC_BTN_END_CREDIT_OK 			1003
#define IDC_BTN_END_CREDIT_CANCEL 		1004
#define IDC_STATIC_END_CREDIT_ADD_TEXT 	1005
#define IDC_STATIC_END_CREDIT_SELECT_FONT 1006

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1007
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
